### ISSUE TITLE
Unspecified error uploading a shapefile

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#441]
**List the CGR information**
- CGR version:  0.12.0-SNAPSHOT
- CGR instance (e.g. a URL): https://georegistry.geoprism.net/  with Namibia data

Reported by @armageddon

**Describe the bug (clear and concise)**
Unspecified error when trying to upload provinces to a Namibia dataset.

**To Reproduce**
1. As a .....[role]: Go to 
2. Click on 
3. See error

**Expected behavior (clear and concise)**

**Screenshots**
![image (29).png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/8527d0d1-cf83-4497-ba19-a266a715b8d1)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by jsmethie** [comment]
Logs from the server
`2020-10-06 08:13:18 ERROR DeveloperMessage: java.io.FileNotFoundException: /usr/local/tomcat/temp/nam_missing_46397844701639809973/__MACOSX/._nam_missing_4.cpg (No such file or directory)
LocalizedMessage: An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff.
com.runwaysdk.dataaccess.ProgrammingErrorException: java.io.FileNotFoundException: /usr/local/tomcat/temp/nam_missing_46397844701639809973/__MACOSX/._nam_missing_4.cpg (No such file or directory)
	at net.geoprism.registry.etl.upload.ShapefileImporter.extract(ShapefileImporter.java:195) ~[georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at net.geoprism.registry.etl.upload.ShapefileImporter.getShapefileFromResource(ShapefileImporter.java:137) ~[georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.ShapefileService.getShapefileConfiguration_aroundBody0(ShapefileService.java:76) ~[georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.ShapefileService.getShapefileConfiguration_aroundBody1$advice(ShapefileService.java:99) [georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.ShapefileService.getShapefileConfiguration(ShapefileService.java:1) [georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at net.geoprism.registry.controller.ShapefileController.getShapefileConfiguration(ShapefileController.java:70) [georegistry-server-0.12.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at com.runwaysdk.mvc.DispatcherServlet.dispatch(DispatcherServlet.java:247) [runwaysdk-client-3.2.12.jar:?]
	at com.runwaysdk.mvc.DispatcherServlet.invokeControllerAction(DispatcherServlet.java:155) [runwaysdk-client-3.2.12.jar:?]
	at com.runwaysdk.controller.URLConfigurationManager$ControllerMapping$ActionMapping.performRequest(URLConfigurationManager.java:660) [runwaysdk-client-3.2.12.jar:?]
	at com.runwaysdk.mvc.DispatcherServlet.checkAndDispatch(DispatcherServlet.java:122) [runwaysdk-client-3.2.12.jar:?]
	at com.runwaysdk.mvc.DelegatingServlet.delegate(DelegatingServlet.java:83) [runwaysdk-client-3.2.12.jar:?]
	at com.runwaysdk.mvc.DelegatingServlet.doPost(DelegatingServlet.java:66) [runwaysdk-client-3.2.12.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:?]
	at com.runwaysdk.web.filter.NoExtensionDispatchFilter.doFilter(NoExtensionDispatchFilter.java:81) [runwaysdk-client-3.2.12.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.58]
	at net.geoprism.SessionFilter.doFilter(SessionFilter.java:111) [geoprism-client-0.9.13.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.58]
	at net.geoprism.EncodingFilter.doFilter(EncodingFilter.java:47) [geoprism-client-0.9.13.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.58]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.58]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.58]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:668) [catalina.jar:8.5.58]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:8.5.58]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.58]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:8.5.58]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.58]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.58]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616) [tomcat-coyote.jar:8.5.58]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.58]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-coyote.jar:8.5.58]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626) [tomcat-coyote.jar:8.5.58]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.58]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.58]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.io.FileNotFoundException: /usr/local/tomcat/temp/nam_missing_46397844701639809973/__MACOSX/._nam_missing_4.cpg (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_265]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_265]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_265]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_265]
	at net.geoprism.registry.etl.upload.ShapefileImporter.extract(ShapefileImporter.java:182) ~[georegistry-server-0.12.0-SNAPSHOT.jar:?]
	... 43 more`

**Comment by jsmethie** [comment]
As can be seen from the logs the zip file is corrupt.  It contains some file reference to files that do not exist.

**Comment by justinlewis** [comment]
@armageddon can you please try un-compressing the zip and re-compressing the files before trying again?

**Comment by justinlewis** [comment]
We determined that this is something unique to zipping that data on his Apple laptop. It was not an issue when compressed on Ubuntu and Windows. This is outside of the control of the CGR so I'm closing this.
