### ISSUE TITLE
Refreshing master list for Focus Areas on Demo throws error

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#54]
**Describe the bug**
When refreshing the Focus Area master list on the demo server with Thailand data the refresh seems to nearly finish but then throws this error:

_[6bda40c8-9700-4c3a-91b7-8a73dd0005f1] is out of date - please update and try your operation again._

**To Reproduce**
1. Go to the Focus Area master list on the Demo server
2. Click the refresh button
3. Wait as the list is refreshing

**Expected behavior**
I expected the master list to refresh with any updated values

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04 LTS
 - Browser chrome
 - Version Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by rrowlands** [comment]
<log4j:event logger="com.runwaysdk.session.AbstractRequestManagement" timestamp="1578480192324" level="INFO" thread="http-bio-8443-exec-164">^M
<log4j:message><![CDATA[DeveloperMessage: Object [6bda40c8-9700-4c3a-91b7-8a73dd0005f1] is stale and cannot be updated.
LocalizedMessage: [6bda40c8-9700-4c3a-91b7-8a73dd0005f1] is out of date - please update and try your operation again.]]></log4j:message>^M
<log4j:throwable><![CDATA[com.runwaysdk.dataaccess.StaleEntityException: Object [6bda40c8-9700-4c3a-91b7-8a73dd0005f1] is stale and cannot be updated.^M
        at com.runwaysdk.dataaccess.database.EntityDAOFactory.update(EntityDAOFactory.java:818)^M
        at com.runwaysdk.dataaccess.EntityDAO.update(EntityDAO.java:1222)^M
        at com.runwaysdk.dataaccess.EntityDAO.save_aroundBody6(EntityDAO.java:1017)^M
        at com.runwaysdk.dataaccess.EntityDAO.save(EntityDAO.java:1)^M
        at com.runwaysdk.dataaccess.ElementDAO.save_aroundBody12(ElementDAO.java:142)^M
        at com.runwaysdk.dataaccess.ElementDAO.save(ElementDAO.java:1)^M
        at com.runwaysdk.dataaccess.ElementDAO.save_aroundBody2(ElementDAO.java:107)^M
        at com.runwaysdk.dataaccess.ElementDAO.save_aroundBody4(ElementDAO.java:1)^M
        at com.runwaysdk.dataaccess.ElementDAO.save_aroundBody5$advice(ElementDAO.java:352)^M
        at com.runwaysdk.dataaccess.ElementDAO.save_aroundBody6(ElementDAO.java:107)^M
        at com.runwaysdk.dataaccess.ElementDAO.save(ElementDAO.java:1)^M
        at com.runwaysdk.dataaccess.BusinessDAO.save_aroundBody0(BusinessDAO.java:870)^M
        at com.runwaysdk.dataaccess.BusinessDAO.save(BusinessDAO.java:1)^M
        at com.runwaysdk.dataaccess.EntityDAO.apply_aroundBody12(EntityDAO.java:1258)^M
        at com.runwaysdk.dataaccess.EntityDAO.apply(EntityDAO.java:1)^M
        at com.runwaysdk.business.Element.userLock(Element.java:371)^M
        at com.runwaysdk.business.Element.lock_aroundBody0(Element.java:387)^M
        at com.runwaysdk.business.Element.lock(Element.java:1)^M
        at net.geoprism.registry.MasterListVersion.publish_aroundBody8(MasterListVersion.java:577)^M
        at net.geoprism.registry.MasterListVersion.publish_aroundBody10(MasterListVersion.java:1)^M
        at net.geoprism.registry.MasterListVersion.publish_aroundBody11$advice(MasterListVersion.java:929)^M
        at net.geoprism.registry.MasterListVersion.publish(MasterListVersion.java:1)^M
        at net.geoprism.registry.service.MasterListService.publish_aroundBody8(MasterListService.java:125)^M
        at net.geoprism.registry.service.MasterListService.publish_aroundBody9$advice(MasterListService.java:101)^M
        at net.geoprism.registry.service.MasterListService.publish(MasterListService.java:1)^M
        at net.geoprism.registry.controller.MasterListController.publish(MasterListController.java:104)^M
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)^M
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)^M
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)^M
        at java.lang.reflect.Method.invoke(Method.java:498)^M
        at com.runwaysdk.mvc.DispatcherServlet.dispatch(DispatcherServlet.java:249)^M
        at com.runwaysdk.mvc.DispatcherServlet.invokeControllerAction(DispatcherServlet.java:157)^M
        at com.runwaysdk.controller.URLConfigurationManager$ControllerMapping$ActionMapping.performRequest(URLConfigurationManager.java:660)^M
        at com.runwaysdk.mvc.DispatcherServlet.checkAndDispatch(DispatcherServlet.java:124)^M
        at com.runwaysdk.mvc.DelegatingServlet.delegate(DelegatingServlet.java:83)^M
        at com.runwaysdk.mvc.DelegatingServlet.doPost(DelegatingServlet.java:66)^M
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)^M
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)^M
        at com.runwaysdk.web.filter.NoExtensionDispatchFilter.doFilter(NoExtensionDispatchFilter.java:81)^M
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)^M
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)^M
        at net.geoprism.SessionFilter.doFilter(SessionFilter.java:111)^M
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)^M
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)^M
        at net.geoprism.EncodingFilter.doFilter(EncodingFilter.java:47)^M
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)^M
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)^M
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)^M
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)^M
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)^M

**Comment by rrowlands** [comment]
This happens when the same masterlist is published more than once at the same time. The original masterlist publish request finishes successfully, and all subsequent publish requests wait for the original publish request to finish, and then after the first request finishes they fail with this StaleEntityException.

This brings up some weird / inconsistent behavior in Runway relating to locks. Sometimes it appears as if Runway will immediately throw a LockException, and sometimes (as is the case in this scenario) the system waits to acquire the lock, and then after it acquires the lock it immediately throws a StaleEntityException.

There are a few different solutions to this problem:
1. Figure out should we be waiting or immediately throwing a LockException? If we should be waiting, then Runway shouldn't be throwing a StaleEntityException
2. If we should be waiting, then for this particular ticket, we probably don't want to wait anyway. So we need a tryLock or isLocked method which we can call. If it's already locked, then we throw an exception telling the user that somebody else is already publishing the masterlist and they can't publish it right now.
3. Masterlists should probably be part of the scheduled job architecture. If we wrap this code in a scheduled job, then we have two additional possible solutions. If we want to wait, then we can just queue the job and tell the user it's queued. If we don't want to wait, then we can query for an existing job and if we find one tell the user they can't publish.
4. If we don't want to let the user publish if a publish is already in progress, then we should probably consider disabling the publish button in the UI so they can't even click the button. Although this potentially may get confusing if they can't publish and they have no idea why. They should ideally have some sort of indication as to what's happening.

**Comment by CarlyNel** [comment]
Hi @justinlewis and @rrowlands. It appears that suggestion number 3 above has already been implemented. Could you please confirm if this is correct and if this ticket should be closed? Or is there anything additional still outstanding or needing feedback on? Many thanks.

**Comment by justinlewis** [comment]
@CarlyNel We'll look into this in Sprint 9.
