### ISSUE TITLE
Exporting Shapefile on Prod is failing

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#572]
When I attempt to export the Province master list (MOHA) for 4/18/2007 (published on 3/14/2021) as a shapefile the server is returning the following error:

```
{"localizedMessage":"An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff.","developerMessage":"An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff.","dto_type":"com.runwaysdk.RunwayExceptionDTO","wrappedException":"com.runwaysdk.RunwayExceptionDTO"}
```

The following error is found in app.log:

```
com.runwaysdk.dataaccess.ProgrammingErrorException: java.io.IOException: Current fid index is null, next must be called before write()
	at net.geoprism.registry.shapefile.MasterListShapefileExporter.writeToFile(MasterListShapefileExporter.java:185) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.shapefile.MasterListShapefileExporter.export(MasterListShapefileExporter.java:202) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.GeoRegistryUtil.exportMasterListShapefile_aroundBody4(GeoRegistryUtil.java:80) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.GeoRegistryUtil.exportMasterListShapefile_aroundBody6(GeoRegistryUtil.java:1) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.GeoRegistryUtil.exportMasterListShapefile_aroundBody7$advice(GeoRegistryUtil.java:929) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.GeoRegistryUtil.exportMasterListShapefile(GeoRegistryUtil.java:1) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.MasterListService.exportShapefile_aroundBody32(MasterListService.java:284) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.MasterListService.exportShapefile_aroundBody33$advice(MasterListService.java:99) [georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.service.MasterListService.exportShapefile(MasterListService.java:1) [georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at net.geoprism.registry.controller.MasterListController.exportShapefile(MasterListController.java:182) [georegistry-server-0.13.4-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at com.runwaysdk.mvc.DispatcherServlet.dispatch(DispatcherServlet.java:247) [runwaysdk-client-3.2.17.jar:?]
	at com.runwaysdk.mvc.DispatcherServlet.invokeControllerAction(DispatcherServlet.java:155) [runwaysdk-client-3.2.17.jar:?]
	at com.runwaysdk.controller.URLConfigurationManager$ControllerMapping$ActionMapping.performRequest(URLConfigurationManager.java:660) [runwaysdk-client-3.2.17.jar:?]
	at com.runwaysdk.mvc.DispatcherServlet.checkAndDispatch(DispatcherServlet.java:122) [runwaysdk-client-3.2.17.jar:?]
	at com.runwaysdk.mvc.DelegatingServlet.delegate(DelegatingServlet.java:83) [runwaysdk-client-3.2.17.jar:?]
	at com.runwaysdk.mvc.DelegatingServlet.doGet(DelegatingServlet.java:72) [runwaysdk-client-3.2.17.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:?]
	at com.runwaysdk.web.filter.NoExtensionDispatchFilter.doFilter(NoExtensionDispatchFilter.java:81) [runwaysdk-client-3.2.17.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.63]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.63]
	at net.geoprism.SessionFilter.doFilter(SessionFilter.java:111) [geoprism-client-0.9.21.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.63]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.63]
	at net.geoprism.EncodingFilter.doFilter(EncodingFilter.java:47) [geoprism-client-0.9.21.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.63]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.63]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.63]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.63]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:669) [catalina.jar:8.5.63]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:8.5.63]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.63]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.63]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.63]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:353) [catalina.jar:8.5.63]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616) [tomcat-coyote.jar:8.5.63]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.63]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831) [tomcat-coyote.jar:8.5.63]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629) [tomcat-coyote.jar:8.5.63]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.63]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.63]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.io.IOException: Current fid index is null, next must be called before write()
	at org.geotools.data.shapefile.fid.IndexedFidWriter.write(IndexedFidWriter.java:243) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:97) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.ShapefileFeatureWriter.close(ShapefileFeatureWriter.java:244) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.close(IndexedShapefileFeatureWriter.java:103) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.InProcessLockingManager$1.close(InProcessLockingManager.java:316) ~[gt-main-19.4.jar:?]
	at org.geotools.data.store.DiffTransactionState.commit(DiffTransactionState.java:196) ~[gt-data-19.4.jar:?]
	at org.geotools.data.DefaultTransaction.commit(DefaultTransaction.java:166) ~[gt-main-19.4.jar:?]
	at net.geoprism.registry.shapefile.MasterListShapefileExporter.writeToFile(MasterListShapefileExporter.java:178) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	... 47 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 490
	at com.vividsolutions.jts.geom.impl.PackedCoordinateSequence$Double.getOrdinate(PackedCoordinateSequence.java:330) ~[jts-1.13.jar:?]
	at org.geotools.data.shapefile.shp.PolygonHandler.write(PolygonHandler.java:450) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.shp.ShapefileWriter.writeNonNullGeometry(ShapefileWriter.java:228) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.shp.ShapefileWriter.writeGeometry(ShapefileWriter.java:200) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.ShapefileFeatureWriter.write(ShapefileFeatureWriter.java:427) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:98) ~[gt-shapefile-19.4.jar:?]
	at org.geotools.data.InProcessLockingManager$1.write(InProcessLockingManager.java:304) ~[gt-main-19.4.jar:?]
	at org.geotools.data.store.DiffTransactionState.commit(DiffTransactionState.java:180) ~[gt-data-19.4.jar:?]
	at org.geotools.data.DefaultTransaction.commit(DefaultTransaction.java:166) ~[gt-main-19.4.jar:?]
	at net.geoprism.registry.shapefile.MasterListShapefileExporter.writeToFile(MasterListShapefileExporter.java:178) ~[georegistry-server-0.13.4-SNAPSHOT.jar:?]
	... 47 more
```

**Comment by rrowlands** [comment]
[A quick google of the error mentions that it might be caused by either an encoding issue in the geometries or perhaps some strange character.](https://stackoverflow.com/questions/52440601/geotoolscurrent-fid-index-is-null-next-must-be-called-before-write)

Furthermore, since other masterlists are able to export just fine to Shapefile I would agree that this is either a quirk specific to Geotools or a specific geometry.

**Comment by SteeveEbener** [comment]
I just tested this under 0.14.0 after creating a list for  4/18/2007 and had no problems exporting and using the shapefile

**Comment by rrowlands** [comment]
Agreed. I just tested this and found the same thing. Let's put this on ice and keep an eye on it.
