### ISSUE TITLE
Unspecified error is thrown when trying to create a relationship with a parent that is not active

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#607]
When specifying a parent on the GeoObject modal, text lookup assist shows me a parent that is not active, but it is implying that I can create a parent relationship. When attempting to persist the GeoObject, an unspecified error is thrown.

Suggested solution (do both): 
* default status to Active when creating a GeoObject.
* throw a more informative exception

**Comment by jsmethie** [comment]
Cause by a serialization issue with a NULL status:

```
com.runwaysdk.dataaccess.ProgrammingErrorException: java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179) ~[gson-2.8.6.jar:?]
	at org.commongeoregistry.adapter.dataaccess.AttributeTerm.fromJSON(AttributeTerm.java:153) ~[cgradapter-common-0.14.4.jar:?]
	at org.commongeoregistry.adapter.dataaccess.GeoObjectJsonAdapters$GeoObjectDeserializer.deserialize(GeoObjectJsonAdapters.java:107) ~[cgradapter-common-0.14.4.jar:?]
	at org.commongeoregistry.adapter.dataaccess.GeoObjectJsonAdapters$GeoObjectDeserializer.deserialize(GeoObjectJsonAdapters.java:49) ~[cgradapter-common-0.14.4.jar:?]
```

**Comment by SteeveEbener** [comment]
Most probably a cuplicate of ticket #495
