### ISSUE TITLE
External synch DHIS2 OAuth credential failure not reported correctly

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#730]
**To reproduce:**
1. Setup an external system configuration to DHIS2 using OAuth. 
2. TODO:  define how to break this connect. I'm still working with the person who reported the original issue to determine the cause.
2. Setup a synchronization that pushes data to DHIS2 and run it.
3. ERROR: if an error an authentication error is thrown you will see that there are errors detail is empty (see screenshot)
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/559de7b7-309d-4962-934f-498b32e370ed)

I determined this is likely an authentication issue because an error is still returned to the browser
`{jobType: "net.geoprism.registry.etl.export.DataExportJob", status: "FAILURE", author: "Tolkien_SRA",…}
author: "Tolkien_SRA"
configuration: "82a2c67b-c66f-441c-bcec-89246b000632"
createDate: "2022-01-09"
exception: {type: "com.runwaysdk.RunwayExceptionDTO",…}
message: "An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff."
type: "com.runwaysdk.RunwayExceptionDTO"
exportErrors: {count: 0, pageNumber: 1, pageSize: 10, resultSet: []}
exportedRecords: null
historyId: "0fc43991-e778-4503-b296-9e5be8000638"
jobId: "b22c36a3-9399-4b60-a873-abcd44000637"
jobType: "net.geoprism.registry.etl.export.DataExportJob"
lastUpdateDate: "2022-01-09"
stage: "EXPORT"
status: "FAILURE"
workProgress: 0
workTotal: 0`

But it reports an unspecified error on the backend. From the backend logs I found this:

`Caused by: com.runwaysdk.business.SmartExceptionDTO: The CGR encountered an error while communicating with the external system. Check to make sure that your connection information is correct and that the remote server is up and responding.
	at com.runwaysdk.business.ComponentDTOFacade.newSmartExceptionDTO(ComponentDTOFacade.java:762) ~[runwaysdk-common-3.4.20.jar:?]
	at com.runwaysdk.session.RequestManagement.processException(RequestManagement.aj:214) ~[runwaysdk-server-3.4.20.jar:?]
	at com.runwaysdk.session.RequestManagement.ajc$inlineAccessMethod$com_runwaysdk_session_RequestManagement$com_runwaysdk_session_RequestManagement$processException(RequestManagement.aj:1) ~[runwaysdk-server-3.4.20.jar:?]
	at net.geoprism.registry.service.SynchronizationConfigService.getConfigForExternalSystem_aroundBody9$advice(SynchronizationConfigService.java:150) ~[georegistry-server-0.18.0.jar:?]
	at net.geoprism.registry.service.SynchronizationConfigService.getConfigForExternalSystem(SynchronizationConfigService.java:1) ~[georegistry-server-0.18.0.jar:?]
	at net.geoprism.registry.controller.SynchronizationConfigController.getConfigForExternalSystem(SynchronizationConfigController.java:52) ~[georegistry-server-0.18.0.jar:?]
	... 41 more`

**Expected Behavior**
This authentication error should be reported to the frontend error object.

**Comment by justinlewis** [comment]
This also occured when getting an error from DHIS2 that the destination root object couldn't be created because one already existed so I think that no errors are being rendered to the frontend. The error itself is available in the JSON response from the server.
