### ISSUE TITLE
Lists and spatial data module stuck when refreshing a list for a Geo-Object Type synchronized with DHIS2

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#743]
**List the CGR information**
- CGR version: v0.18.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
A "DHIS2 Country (mSupply)" Geo-Object Type was recently created and previously synchronized to test the DHIS2 integration, however, when we try to refresh the working version for one of the lists for this to see edits made from within the GPR, a white loading bar shows up and nothing happens.

**To Reproduce**
1. As a System Administrator: Go to the Lists and spatial data module.
2. Open the Working Version for a list for the DHIS2 County (mSupply) Geo-Object Type. 
3. Edit a Geo-Object and submit the changes.
4. Refresh the list.
5. The loading bar shows but does not progress.

**Expected behavior (clear and concise)**
The loading bar progresses and the list refreshes.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/1e6a84a6-ba8a-42c9-9c03-89044e0aaa79)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 98.0.4758.102

**Additional context (if any)**
Logged in using the Tolkien_SRA account.

**Comment by jsmethie** [comment]
Stack trace:
2022-04-12 19:43:10 ERROR An error occurred while executing job [] - . The master list can not be republished because the hierarchy has changed
com.runwaysdk.business.SmartExceptionDTO: The master list can not be republished because the hierarchy has changed
	at com.runwaysdk.business.ComponentDTOFacade.newSmartExceptionDTO(ComponentDTOFacade.java:762) ~[runwaysdk-common-3.4.31.jar:?]
	at com.runwaysdk.session.RequestManagement.processException(RequestManagement.aj:214) ~[runwaysdk-server-3.4.31.jar:?]
	at com.runwaysdk.session.RequestManagement.ajc$inlineAccessMethod$com_runwaysdk_session_RequestManagement$com_runwaysdk_session_RequestManagement$processException(RequestManagement.aj:1) ~[runwaysdk-server-3.4.31.jar:?]
	at com.runwaysdk.system.scheduler.QuartzRunwayJob.executeAsUser_aroundBody7$advice(QuartzRunwayJob.java:150) ~[runwaysdk-server-3.4.31.jar:?]
	at com.runwaysdk.system.scheduler.QuartzRunwayJob.executeAsUser(QuartzRunwayJob.java:1) ~[runwaysdk-server-3.4.31.jar:?]
	at com.runwaysdk.system.scheduler.QuartzRunwayJob.execute(QuartzRunwayJob.java:173) [runwaysdk-server-3.4.31.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]

**Comment by jsmethie** [comment]
The root issue is that if an error occurs when refreshing a list the user is never notified.  In this particular instance the error is a valid error message that the user must see.
